# These are supported funding model platforms
open_collective: flutter-webrtc
ko_fi: cloudwebrtc
issuehunt: cloudwebrtc
patreon: cloudwebrtc
custom: ['https://www.buymeacoffee.com/cloudwebrtc','https://www.paypal.me/duanweiwei']
