# Project configuration for rustfmt Rust code formatter.
# See full list of configurations at:
# https://github.com/rust-lang/rustfmt/blob/master/Configurations.md

max_width = 80
use_small_heuristics = "Max"

group_imports = "StdExternalCrate"
imports_granularity = "Crate"

format_strings = false
format_code_in_doc_comments = true
format_macro_matchers = true
use_try_shorthand = true

error_on_line_overflow = true
error_on_unformatted = true

unstable_features = true
