// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.10.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import '../../../frb_generated.dart';
import '../../../lib.dart';
import '../../media_stream_track.dart';
import '../../media_stream_track/media_type.dart';
import '../../transceiver.dart';
import '../../transceiver/direction.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`

/// Representation of a track event, sent when a new [`MediaStreamTrack`] is
/// added to an [`RtcRtpTransceiver`] as part of a [`PeerConnection`].
class RtcTrackEvent {
  /// [`MediaStreamTrack`] associated with the [RTCRtpReceiver] identified
  /// by the receiver.
  ///
  /// [RTCRtpReceiver]: https://w3.org/TR/webrtc#dom-rtcrtpreceiver
  final MediaStreamTrack track;

  /// [`RtcRtpTransceiver`] object associated with the event.
  final RtcRtpTransceiver transceiver;

  const RtcTrackEvent({required this.track, required this.transceiver});

  @override
  int get hashCode => track.hashCode ^ transceiver.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RtcTrackEvent &&
          runtimeType == other.runtimeType &&
          track == other.track &&
          transceiver == other.transceiver;
}
