// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import 'frb_generated.dart';

// Rust type: RustOpaqueMoi<Arc < PeerConnection >>
abstract class ArcPeerConnection implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<Arc < RtpEncodingParameters >>
abstract class ArcRtpEncodingParameters implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<Arc < RtpParameters >>
abstract class ArcRtpParameters implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<Arc < RtpTransceiver >>
abstract class ArcRtpTransceiver implements RustOpaqueInterface {}
