// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.10.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;

import '../../frb_generated.dart';

part 'track_event.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `eq`, `fmt`

@freezed
sealed class TrackEvent with _$TrackEvent {
  const TrackEvent._();

  /// Ended event of the [`MediaStreamTrack`] interface is fired when playback
  /// or streaming has stopped because the end of the media was reached or
  /// because no further data is available.
  const factory TrackEvent.ended() = TrackEvent_Ended;

  /// Event indicating an audio level change in the [`MediaStreamTrack`].
  const factory TrackEvent.audioLevelUpdated(int field0) =
      TrackEvent_AudioLevelUpdated;

  /// Event indicating that the [`MediaStreamTrack`] has completely
  /// initialized and can be used on Flutter side.
  const factory TrackEvent.trackCreated() = TrackEvent_TrackCreated;
}
