// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.10.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;

import '../../frb_generated.dart';

part 'rtc_outbound_rtp_stream_media_type.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`

@freezed
sealed class RtcOutboundRtpStreamStatsMediaType
    with _$RtcOutboundRtpStreamStatsMediaType {
  const RtcOutboundRtpStreamStatsMediaType._();

  /// `audio` media type fields.
  const factory RtcOutboundRtpStreamStatsMediaType.audio({
    /// Total number of samples that have been sent over the RTP stream.
    BigInt? totalSamplesSent,

    /// Whether the last RTP packet sent contained voice activity or not
    /// based on the presence of the V bit in the extension header.
    bool? voiceActivityFlag,
  }) = RtcOutboundRtpStreamStatsMediaType_Audio;

  /// `video` media type fields.
  const factory RtcOutboundRtpStreamStatsMediaType.video({
    /// Width of the last encoded frame.
    ///
    /// The resolution of the encoded frame may be lower than the media
    /// source (see [RTCVideoSourceStats.width][1]).
    ///
    /// Before the first frame is encoded this attribute is missing.
    ///
    /// [1]: https://w3.org/TR/webrtc-stats#dom-rtcvideosourcestats-width
    int? frameWidth,

    /// Height of the last encoded frame.
    ///
    /// The resolution of the encoded frame may be lower than the media
    /// source (see [RTCVideoSourceStats.height][1]).
    ///
    /// Before the first frame is encoded this attribute is missing.
    ///
    /// [1]: https://w3.org/TR/webrtc-stats#dom-rtcvideosourcestats-height
    int? frameHeight,

    /// Number of encoded frames during the last second.
    ///
    /// This may be lower than the media source frame rate (see
    /// [RTCVideoSourceStats.framesPerSecond][1]).
    ///
    /// [1]: https://tinyurl.com/rrmkrfk
    double? framesPerSecond,
  }) = RtcOutboundRtpStreamStatsMediaType_Video;
}
